version: 2
jobs:
  deploy-staging:
    environment:
      TERRAFORM_COMMAND: apply
      TF_VAR_TERRAFORM_STATE_BUCKET: staq-terraform-state
      TF_VAR_ENVIRONMENT: staging
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - deploy-staging