version: 2
jobs:
  deploy-staging:
    environment:
      TERRAFORM_COMMAND: apply
      TF_VAR_TERRAFORM_STATE_BUCKET: staq-k8s-state
      TF_VAR_ENVIRONMENT: staging
      TF_VAR_NODE_COUNT: 1
      TF_VAR_CLUSTER_NAME: k8s-test-staging
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint
  deploy-prod:
    environment:
      TERRAFORM_COMMAND: apply
      TF_VAR_TERRAFORM_STATE_BUCKET: staq-k8s-state
      TF_VAR_ENVIRONMENT: prod
      TF_VAR_NODE_COUNT: 3
      TF_VAR_CLUSTER_NAME: k8s-test-prod
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - deploy-staging
      - deploy-prod:
          requires:
            - deploy-staging
