version: 2
jobs:
  plan-staging:
    environment:
      TERRAFORM_COMMAND: plan
      TERRAFORM_STATE_BUCKET: staq-k8s-state
      ENVIRONMENT: staging
      TF_VAR_NODE_COUNT: 1
      TF_VAR_CLUSTER_NAME: k8s-lab-staging
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint
  deploy-staging:
    environment:
      TERRAFORM_COMMAND: apply
      TERRAFORM_STATE_BUCKET: staq-k8s-state
      ENVIRONMENT: staging
      TF_VAR_NODE_COUNT: 1
      TF_VAR_CLUSTER_NAME: k8s-lab-staging
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint
  plan-prod:
    environment:
      TERRAFORM_COMMAND: plan
      TERRAFORM_STATE_BUCKET: staq-k8s-state
      ENVIRONMENT: prod
      TF_VAR_NODE_COUNT: 1
      TF_VAR_CLUSTER_NAME: k8s-lab-prod
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint
  deploy-prod:
    environment:
      TERRAFORM_COMMAND: apply
      TERRAFORM_STATE_BUCKET: staq-k8s-state
      ENVIRONMENT: prod
      TF_VAR_NODE_COUNT: 1
      TF_VAR_CLUSTER_NAME: k8s-lab-prod
    docker:
      - image: sleyva97/terraform:0.0.1
    steps:
      - checkout
      - run : |
          entrypoint

workflows:
  version: 2
  build-package-deploy:
    jobs:
      - plan-staging
      - deploy-staging:
          requires:
            - plan-staging
      - plan-prod:
            - deploy-staging
      - deploy-prod:
          requires:
            - deploy-staging
